const ROOT='../..';
const giovanni=`${ROOT}/assets/trainer_sprite/trainer_giovanni/Sprite_Giovanni_RFVF.png`;
const trainer=k=>`https://play.pokemonshowdown.com/sprites/trainers/${k}.png`;
const poke=(n,shiny=false)=>`https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/${shiny?'shiny/':''}${n}.png`;
const L=(lang,fr,en)=>lang==='fr'?fr:en;
const PK={rattata:[19,'Rattata'],pidgey:[16,'Pidgey'],pikachu:[25,'Pikachu'],meowth:[52,'Meowth'],zubat:[41,'Zubat'],gastly:[92,'Gastly'],gengar:[94,'Gengar'],nidoking:[34,'Nidoking'],rhydon:[112,'Rhydon'],alakazam:[65,'Alakazam'],arcanine:[59,'Arcanine'],charizard:[6,'Charizard'],dragonite:[149,'Dragonite'],snorlax:[143,'Snorlax'],lapras:[131,'Lapras'],eevee:[133,'Eevee'],gyarados:[130,'Gyarados'],groudon:[383,'Groudon'],kyogre:[382,'Kyogre']};
const chip=(key,{level=18,stars=3,shiny=false}={})=>{const[d,n]=PK[key];return `<div class="pg-poke-chip"><img src="${poke(d,shiny)}" alt="${n}"><small>${n} · Lv.${level}</small><div class="pg-stars">${'★'.repeat(stars)}${'☆'.repeat(5-stars)}</div></div>`};
const tabs=(active,lang,simple=false)=>(simple?[['tabZones','Zones'],['tabPC','Pokémon'],['tabAgents','Agents'],['tabGang','Gang'],['tabMarket',L(lang,'Marché','Market')]]:[['tabZones','Zones'],['tabPC','Pokémon'],['tabAgents','Agents'],['tabMarket',L(lang,'Marché','Market')],['tabGang','Gang'],['tabPokedex','Pokédex'],['tabBattleLog',L(lang,'📋 Évts','📋 Events')],['tabMissions','Missions'],['tabCompetition','⚔ Raids']]).map(([id,n])=>`<div class="pg-tab${active===id?' active':''}">${n}</div>`).join('');
const shell=({lang,active='tabZones',rep=84,money=12650,body,gang='Team Eclipse',simple=false})=>`<div class="shot-scene"><div class="pg-game-shell"><div class="pg-topbar"><span>🏠</span><span class="gang">${gang}</span><span class="stat">₽ <b>${money.toLocaleString(lang==='fr'?'fr-FR':'en-US')}</b></span><span class="stat">⭐ <b>${rep}</b></span><span class="stat">◉ 24</span><span>🔔</span><span>⚙</span></div><div class="pg-tabs">${tabs(active,lang,simple)}</div><div class="pg-content">${body}</div></div></div>`;

function field(lang,mode='capture'){
 const capture=mode==='capture',ambush=mode==='ambush',guide=mode==='guide';
 const inside=`<div class="pg-zone-window" style="left:24px;right:24px;top:20px;bottom:20px;height:auto"><div class="pg-zone-header"><span class="pg-title">${L(lang,'ZONE INCONNUE','UNKNOWN FIELD')}</span><span class="pg-dim">${capture?'10 / 10':ambush?'⚠ TEAM ROCKET':'●'}</span></div>${capture?`<img class="pg-sprite pg-pokemon" style="left:48%;top:37%" src="${poke(52)}"><div class="pg-arrow" style="left:52%;top:25%">↓</div><img class="pg-sprite pg-pokemon" style="left:26%;top:59%;opacity:.72" src="${poke(19)}"><img class="pg-sprite pg-pokemon" style="left:70%;top:56%;opacity:.72" src="${poke(41)}"><div class="pg-speech" style="left:34%;top:9%">${L(lang,'Capture ce que tu peux avant que quelqu’un te remarque.','Catch what you can before someone notices.')}</div>`:''}${ambush?`<img class="pg-sprite pg-trainer" style="left:25%;top:39%" src="${trainer('rocketgrunt')}"><img class="pg-sprite pg-trainer" style="left:46%;top:32%" src="${trainer('rocketgruntf')}"><img class="pg-sprite pg-trainer" style="left:67%;top:41%" src="${trainer('scientist')}"><div class="pg-speech" style="left:33%;top:8%">${L(lang,'Hé ! Personne ne chasse sur ce terrain. Il appartient à quelqu’un.','Hey! Nobody hunts on this field. It belongs to someone.')}</div>`:''}${guide?`<img class="pg-sprite pg-trainer" style="left:52%;top:39%" src="${trainer('rocketgruntf')}"><div class="pg-speech" style="left:34%;top:8%">${L(lang,"Attends ! Me dénonce pas… J'en ai fini avec la Team Rocket. Prends-moi avec toi.","Wait! Don't turn me in… I'm done with Team Rocket. Take me with you.")}</div>`:''}</div>`;
 const modal=ambush?`<div class="pg-modal-backdrop"><div class="pg-modal"><h2>${L(lang,'⚠ EMBUSCADE','⚠ AMBUSH')}</h2><p>${L(lang,'Trois sbires Rocket te barrent la route. Ton équipe Boss a été préparée avec tes meilleurs Pokémon.','Three Rocket grunts block your way. Your Boss team has been prepared with your best Pokémon.')}</p><div class="pg-team-row">${chip('meowth',{level:10})}${chip('gastly',{level:9,stars:4})}${chip('zubat',{level:8,stars:2})}</div><div class="pg-btn-row"><button class="pg-action-btn">${L(lang,'Vérifier l’équipe','Check team')}</button><button class="pg-action-btn primary">${L(lang,'Affronter les sbires','Face the grunts')}</button></div></div></div>`:'';
 const badge=guide?`<div class="pg-guide-badge"><img src="${trainer('rocketgruntf')}"><div><strong>${L(lang,'LE TRANSFUGE','THE DEFECTOR')}</strong><p>${L(lang,'Ton premier Agent. Il devient ensuite ton conseiller.','Your first Agent. He then becomes your advisor.')}</p></div></div>`:'';
 return shell({lang,active:'tabZones',rep:capture?0:8,money:5000,gang:L(lang,'Gang sans nom','Unnamed Gang'),simple:true,body:inside+modal+badge});
}
function zones(lang){const z=[[L(lang,'Route 1','Route 1'),'0 rep',''],[L(lang,'Forêt de Jade','Viridian Forest'),'15 rep','forest'],[L(lang,'Argenta','Pewter City'),'150 rep','city'],[L(lang,'Mont Sélénite','Mt. Moon'),'200 rep',''],[L(lang,'Grotte Taupiqueur',"Diglett's Cave"),'250 rep',''],[L(lang,'Casino de Céladopole','Celadon Casino'),'🎟','special'],[L(lang,'Parc Safari','Safari Zone'),'500 rep','forest'],[L(lang,'Tour Pokémon','Pokémon Tower'),'550 rep','special']];const body=`<div style="padding:12px 16px;border-bottom:1px solid #343b46;display:flex;gap:6px"><span class="pg-action-btn primary">${L(lang,'Tout','All')}</span><span class="pg-action-btn">★ ${L(lang,'Favoris','Favorites')}</span><span class="pg-action-btn">🗺 Routes</span><span class="pg-action-btn">🏙 ${L(lang,'Villes','Cities')}</span><span class="pg-action-btn">⭐ ${L(lang,'Spéciaux','Special')}</span></div><div class="pg-zone-grid">${z.map(([n,m,c],i)=>`<div class="pg-zone-card ${c}${i>3?' locked':''}"><div class="pg-zone-bg"></div><div class="pg-zone-name">${n}</div><div class="meta"><span>${m}</span><span>${i<4?'✓':'🔒'}</span></div></div>`).join('')}</div>`;return shell({lang,rep:184,money:18450,body})}
function agents(lang){const body=`<div class="pg-agent-layout"><div class="pg-panel pg-agent-card"><div class="portrait"><img src="${trainer('rocketgruntf')}"></div><div><div class="pg-title">MAYA · GRUNT</div><div class="pg-dim" style="margin-top:7px">Lv.14 · XP 118 / 420 · Route 1</div><div style="margin-top:9px;font-size:10px">${L(lang,'« Observatrice · Opportuniste »','“Observant · Opportunistic”')}</div><div class="pg-switches"><span class="pg-switch on">✓ ${L(lang,'Capture','Capture')}</span><span class="pg-switch on">✓ ${L(lang,'Combat','Battle')}</span><span class="pg-switch">○ Raid</span><span class="pg-switch on">🔔</span></div><div class="pg-team-row" style="margin-top:13px">${chip('gastly',{level:21,stars:4})}${chip('zubat',{level:17})}</div></div></div><div class="pg-panel" style="padding:15px"><div class="pg-title">${L(lang,'ORGANISATION','ORGANIZATION')}</div><div class="pg-mission-list"><div class="pg-mission"><div class="pg-mission-row"><strong>${L(lang,'Zone assignée','Assigned zone')}</strong><span class="reward">Route 1</span></div><div class="pg-dim" style="font-size:9px;margin-top:6px">${L(lang,'Capture et combat en arrière-plan.','Catches and battles in the background.')}</div></div><div class="pg-mission"><div class="pg-mission-row"><strong>${L(lang,'Prochain grade','Next rank')}</strong><span class="reward">Sergeant · Lv.25</span></div><div class="pg-progress"><span style="width:56%"></span></div></div><button class="pg-action-btn primary">＋ ${L(lang,'Recruter · 15 000₽','Recruit · 15,000₽')}</button></div></div></div>`;return shell({lang,active:'tabAgents',rep:96,money:21800,body})}
function dex(lang,reveal=false){const ids=[1,4,7,10,12,13,15,16,19,23,25,29,32,35,39,41,43,46,48,50,52,54,56,58,63,66,69,72,74,77,79,81,84,88,90,92,95,98,100,102,104,109,111,113,118,120,123,127,129,130,131,133,134,135,136,143,147,148,149];const tiles=ids.map((d,i)=>`<div class="pg-dex-tile${i%11===0?' shiny':''}${i>45?' unknown':''}${reveal&&i<35?' reveal':''}" style="animation-delay:${i*18}ms"><span class="dex-no">#${String(d).padStart(3,'0')}</span><img src="${poke(d,i%11===0)}"></div>`).join('');const body=`<div class="pg-pokedex"><div class="pg-pokedex-head"><div class="pg-title">POKÉDEX — KANTO</div><div class="pg-dex-progress">${reveal?'46':'113'} / 151 · ✨ ${reveal?'3':'12'}</div><button class="pg-action-btn">▦</button><button class="pg-action-btn">▤</button></div><div class="pg-dex-grid">${tiles}</div>${reveal?`<div class="pg-popup shiny"><div style="font-size:30px">📖</div><div><div class="label">${L(lang,'POKÉDEX DÉBLOQUÉ !','POKÉDEX UNLOCKED!')}</div><div class="pg-dim" style="font-size:10px;margin-top:4px">${L(lang,'Tes découvertes sont importées…','Importing your discoveries…')}</div></div></div>`:''}</div>`;return shell({lang,active:'tabPokedex',rep:88,money:12600,body})}
function market(lang){const items=[['🧪',L(lang,'Encens Chance','Lucky Incense'),'2 500₽'],['📡','Rarioscope','4 000₽'],['✨',L(lang,'Aura Shiny','Shiny Aura'),'6 500₽'],['🥚',L(lang,'Incubateur','Incubator'),'8 000₽'],['🍬',L(lang,'Super Bonbon','Rare Candy'),'12 000₽'],['🌑',L(lang,'Marché Noir','Black Market'),'???']];const body=`<div class="pg-market"><div class="pg-panel" style="padding:15px"><div class="pg-title">${L(lang,'MARCHÉ','MARKET')}</div><div class="pg-shop-grid">${items.map(([i,n,p])=>`<div class="pg-shop-card"><div class="icon">${i}</div><strong>${n}</strong><div class="pg-dim" style="font-size:9px">${L(lang,'Ressource pour ton gang.','A resource for your gang.')}</div><div class="pg-price">${p}</div></div>`).join('')}</div></div><div class="pg-panel" style="padding:15px"><div class="pg-title">${L(lang,'NOUVEAUX SERVICES','NEW SERVICES')}</div><div class="pg-mission-list"><div class="pg-mission"><div class="pg-mission-row"><strong>${L(lang,'Auto-vente','Auto-sell')}</strong><span class="reward">25 000₽</span></div></div><div class="pg-mission"><div class="pg-mission-row"><strong>${L(lang,'Marché Noir','Black Market')}</strong><span class="reward">ACTIVE</span></div><div class="pg-progress"><span style="width:72%"></span></div></div></div></div></div>`;return shell({lang,active:'tabMarket',rep:115,money:38200,body})}
function missions(lang){const qs=[[L(lang,'Capturer 5 Pokémon','Catch 5 Pokémon'),'5 / 5','+750₽'],[L(lang,'Gagner 3 combats','Win 3 battles'),'2 / 3','+8 REP'],[L(lang,'Utiliser un Agent','Use an Agent'),'1 / 1','+1 Encens']];const body=`<div class="pg-missions"><div class="pg-panel" style="padding:15px"><div class="pg-title">${L(lang,'MISSIONS ACTIVES','ACTIVE MISSIONS')}</div><div class="pg-mission-list">${qs.map(([n,p,r],i)=>`<div class="pg-mission"><div class="pg-mission-row"><strong>${n}</strong><span class="reward">${r}</span></div><div class="pg-progress"><span style="width:${i===1?66:100}%"></span></div><div class="pg-dim" style="font-size:8px;margin-top:5px">${p}</div></div>`).join('')}</div></div><div class="pg-panel" style="padding:15px"><div class="pg-title">${L(lang,'OBJECTIF DE SESSION','SESSION OBJECTIVE')}</div><div style="font-size:42px;text-align:center;margin-top:40px">🎯</div><div style="text-align:center;margin-top:9px;font-weight:700">${L(lang,'Prendre le contrôle de la Forêt de Jade','Take control of Viridian Forest')}</div><div class="pg-progress" style="margin:18px 20px"><span style="width:82%"></span></div></div></div>`;return shell({lang,active:'tabMissions',rep:321,money:53200,body})}
function gang(lang){const body=`<div class="pg-gang-layout"><div class="pg-panel pg-boss-card"><div class="pg-boss-head"><img src="${trainer('red')}"><div><div class="pg-title">BOSS NOVA</div><div class="pg-dim" style="margin-top:7px">${L(lang,'Stratège de Team Eclipse','Team Eclipse Strategist')}</div><div style="margin-top:8px;color:#f3ca58">⭐ 724 · ₽ 184 200</div></div></div><div class="pg-title">${L(lang,'ÉQUIPE BOSS','BOSS TEAM')}</div><div class="pg-team-row">${chip('gengar',{level:51,stars:5,shiny:true})}${chip('nidoking',{level:46,stars:4})}${chip('rhydon',{level:45})}${chip('alakazam',{level:49,stars:4})}</div></div><div class="pg-panel" style="padding:16px"><div class="pg-title">${L(lang,'VITRINE DU GANG','GANG SHOWCASE')}</div><div class="pg-showcase" style="margin-top:14px">${chip('dragonite',{level:55,stars:5})}${chip('snorlax',{level:52,stars:4})}${chip('lapras',{level:50,stars:4})}${chip('charizard',{level:53,stars:5})}${chip('eevee',{level:28,stars:5,shiny:true})}${chip('gyarados',{level:49,stars:4})}</div></div></div>`;return shell({lang,active:'tabGang',rep:724,money:184200,body})}
function shiny(lang){const body=`<div class="pg-capture-stage"><div class="pg-zone-header"><span class="pg-title">${L(lang,'FORÊT DE JADE','VIRIDIAN FOREST')}</span><span class="pg-dim">CAPTURE</span></div><img class="pg-capture-mon" src="${poke(25,true)}"><div class="pg-capture-stars">★★★★★</div><div class="pg-ball"></div><div class="pg-popup shiny"><img src="${poke(25,true)}"><div><div class="label">✨ SHINY PIKACHU !</div><div class="pg-dim" style="font-size:10px;margin-top:4px">${L(lang,'Potentiel ★★★★★ · Capture critique','★★★★★ potential · Critical catch')}</div></div></div></div>`;return shell({lang,rep:184,money:21400,body})}
function unlock(lang){const body=`<div class="pg-zone-grid">${[['Route 1','✓'],[L(lang,'Forêt de Jade','Viridian Forest'),'✓'],[L(lang,'Argenta','Pewter City'),'🔒'],[L(lang,'Mont Sélénite','Mt. Moon'),'🔒']].map(([n,s],i)=>`<div class="pg-zone-card ${i===1?'forest':''}${i>1?' locked':''}"><div class="pg-zone-bg"></div><div class="pg-zone-name">${n}</div><div class="meta"><span>${i*15} rep</span><span>${s}</span></div></div>`).join('')}</div><div class="pg-modal-backdrop"><div class="pg-modal pg-unlock"><div class="big">🗺 ${L(lang,'ZONE DÉBLOQUÉE !','ZONE UNLOCKED!')}</div><div class="zone">${L(lang,'Forêt de Jade','Viridian Forest')}</div><div class="rep">⭐ 15 REP</div><div class="pg-btn-row" style="justify-content:center"><button class="pg-action-btn primary">→ ${L(lang,'Aller à la zone','Go to zone')}</button><button class="pg-action-btn">${L(lang,'Plus tard','Later')}</button></div></div></div>`;return shell({lang,rep:18,money:6900,body,simple:true})}
function rare(lang){const body=`<div class="pg-zone-grid">${[['Route 1','✓'],[L(lang,'Forêt de Jade','Viridian Forest'),'✓'],[L(lang,'Argenta','Pewter City'),'🔒'],[L(lang,'Mont Sélénite','Mt. Moon'),'🔒']].map(([n,s],i)=>`<div class="pg-zone-card ${i===1?'forest':''}${i>1?' locked':''}"><div class="pg-zone-bg"></div><div class="pg-zone-name">${n}</div><div class="meta"><span>${i*15} rep</span><span>${s}</span></div></div>`).join('')}</div><div class="pg-popup rare"><img src="${poke(25)}"><div><div class="label">⚡ ${L(lang,'Pokémon rare aperçu : Pikachu','Rare sighting: Pikachu')}</div><div class="pg-dim" style="font-size:10px;margin-top:4px">→ ${L(lang,'Forêt de Jade','Viridian Forest')}</div></div></div>`;return shell({lang,rep:64,money:8500,body})}
function legendary(lang,key){const[d,n]=PK[key];const body=`<div class="pg-legendary-stage"><div class="pg-hpbox enemy"><div class="pg-hpname">${n.toUpperCase()} · Lv.70</div><div class="pg-hpbar"><span style="width:62%"></span></div></div><img class="enemy" src="${poke(d)}"><img class="player" src="${poke(94)}"><div class="pg-hpbox player"><div class="pg-hpname">GENGAR · Lv.58</div><div class="pg-hpbar"><span style="width:73%"></span></div></div><div class="pg-battle-actions"><div class="pg-dialogbox">${L(lang,`${n} apparaît directement dans la zone. Jusqu’à 3 Agents peuvent l’affaiblir avant l’entrée du Boss.`,`${n} appears directly in the zone. Up to 3 Agents can soften it up before the Boss enters.`)}</div><div class="pg-action-grid"><button>${L(lang,'ATTAQUE','FIGHT')}</button><button>${L(lang,'ÉQUIPE','TEAM')}</button><button>${L(lang,'OBJET','ITEM')}</button><button>${L(lang,'FUITE','RUN')}</button></div></div></div>`;return shell({lang,rep:1320,money:420500,body})}
function identity(lang){return `<div class="shot-scene"><div class="pg-giovanni"><img class="portrait" src="${giovanni}"><div class="pg-giovanni-content"><div class="pg-team-row">${chip('meowth',{level:10})}${chip('gastly',{level:9,stars:4})}${chip('zubat',{level:8,stars:2})}</div></div><div class="pg-giovanni-dialog"><div class="pg-giovanni-name">GIOVANNI</div><div>${L(lang,"Pas mal. Mais je ne sais même pas encore à qui j'ai affaire…","Not bad. But I don't even know who I'm dealing with yet…")}</div><input class="pg-input" value="Nova"><div class="pg-btn-row"><button class="pg-action-btn primary">${L(lang,'Continuer','Continue')} →</button></div></div></div></div>`}
function cover(lang){
 const mons=[
  {d:6,left:'15%',top:'70%',w:192},
  {d:94,left:'85%',top:'70%',w:192},
  {d:149,left:'50%',top:'60%',w:96},
 ];
 const monsHtml=mons.map(m=>`<img class="pg-cover-mon" style="left:${m.left};top:${m.top};width:${m.w}px;height:${m.w}px;transform:translate(-50%,-50%)" src="${poke(m.d)}">`).join('');
 return `<div class="shot-scene"><div class="pg-cover">
  <div class="pg-cover-grid"></div>
  <img class="pg-cover-logo-neg" src="${ROOT}/assets/pokegang_logo/pokegang_logo_full_B.png">
  <img class="pg-cover-boss" style="left:50%;top:50%;width:30%;transform:translate(-50%,-50%)" src="${trainer('red')}">
  <img class="pg-cover-boss" style="left:22%;top:47%;width:18%;transform:translate(-50%,-50%);opacity:.4" src="${trainer('rocketgrunt')}">
  <img class="pg-cover-boss" style="left:78%;top:47%;width:18%;transform:translate(-50%,-50%);opacity:.4" src="${trainer('rocketgruntf')}">
  <div class="pg-cover-shade-top"></div>
  <div class="pg-cover-shade-bottom"></div>
  <div class="pg-cover-corner" style="left:14px;top:14px">⭐ <b>724</b> REP</div>
  <div class="pg-cover-corner" style="right:14px;top:14px">₽ <b>184,200</b></div>
  <div class="pg-cover-head"><img class="pg-cover-title-logo" src="${ROOT}/assets/pokegang_logo/pokegang_logo_full_B.png" alt="PokéGang"><div class="pg-cover-sub">Gotta rule ’em all</div></div>
  <div class="pg-cover-stage">${monsHtml}<div class="pg-cover-ball"></div></div>
  <div class="pg-cover-tagwrap">${L(lang,'CAPTURE','CATCH')}<span class="dot">·</span>${L(lang,'RECRUTE','RECRUIT')}<span class="dot">·</span>${L(lang,'ÉTENDS','EXPAND')}</div>
 </div></div>`;
}

export const SCENES=[
['itch-cover','🎴','Marketing',{fr:'Cover itch.io',en:'Itch.io cover'},{fr:'Clé visuelle 630×500',en:'630×500 key art'},{fr:'Composition promo avec les vrais sprites, l’équipe Boss et la Ball du jeu. Choisir 630×500 en format personnalisé puis « Ouvrir clean » pour la capture.',en:'Promo composition using the game’s real sprites, Boss team and Ball. Set 630×500 as a custom size, then “Open clean” for the capture.'},cover],
['onboarding-first-catch','🌿','Onboarding',{fr:'Première capture',en:'First capture'},{fr:'Zone inconnue + flèche',en:'Unknown Field + arrow'},{fr:'Première interaction du nouveau tunnel.',en:'First interaction of the new onboarding funnel.'},l=>field(l,'capture')],
['onboarding-ambush','🚀','Onboarding',{fr:'Embuscade Team Rocket',en:'Team Rocket ambush'},{fr:'Sbires + popup de défi',en:'Grunts + challenge popup'},{fr:'Les trois sbires et le combat scénarisé.',en:'The three grunts and scripted fight.'},l=>field(l,'ambush')],
['onboarding-giovanni','🕴️','Onboarding',{fr:'Giovanni — identité',en:'Giovanni — identity'},{fr:'Création Boss / gang',en:'Boss / gang creation'},{fr:'Écran narratif après l’embuscade.',en:'Narrative identity screen after the ambush.'},identity],
['onboarding-guide','🕵️','Onboarding',{fr:'Le transfuge',en:'The defector'},{fr:'Premier Agent + conseiller',en:'First Agent + advisor'},{fr:'Le sbire qui rejoint le gang.',en:'The grunt who joins the gang.'},l=>field(l,'guide')],
['zones-progressive','🗺️','Progression',{fr:'Zones révélées progressivement',en:'Progressive zone reveal'},{fr:'Fog map début / milieu',en:'Early / mid-game fog map'},{fr:'Carte avec révélation progressive.',en:'Map with progressive reveal.'},zones],
['pokedex-reveal','📖','Progression',{fr:'Déblocage du Pokédex',en:'Pokédex unlock'},{fr:'Cascade des espèces',en:'Species reveal cascade'},{fr:'Nouveau déblocage narratif du Pokédex.',en:'New narrative Pokédex unlock.'},l=>dex(l,true)],
['pokedex-filled','🔎','Interface',{fr:'Pokédex rempli',en:'Filled Pokédex'},{fr:'Grille + shinies',en:'Grid + shinies'},{fr:'Vue dense de collection.',en:'Dense collection view.'},l=>dex(l,false)],
['agents-management','👥','Interface',{fr:'Gestion des Agents',en:'Agent management'},{fr:'Équipe, zone, comportements',en:'Team, zone, behaviours'},{fr:'Carte Agent avec flags interactifs.',en:'Agent card with interactive flags.'},agents],
['market','💰','Interface',{fr:'Marché',en:'Market'},{fr:'Objets, boosts, marché noir',en:'Items, boosts, black market'},{fr:'Présentation du Marché post-onboarding.',en:'Post-onboarding Market view.'},market],
['missions','🎯','Interface',{fr:'Missions',en:'Missions'},{fr:'Quêtes + objectif session',en:'Quests + session objective'},{fr:'Missions préremplies pour une capture claire.',en:'Prefilled missions for a clear shot.'},missions],
['gang-showcase','💀','Interface',{fr:'Boss & Gang',en:'Boss & Gang'},{fr:'Équipe Boss + vitrine',en:'Boss team + showcase'},{fr:'Vue avancée du gang.',en:'Advanced gang view.'},gang],
['capture-shiny','✨','Feedback',{fr:'Capture shiny',en:'Shiny capture'},{fr:'Ball wobble + étoiles',en:'Ball wobble + stars'},{fr:'Refonte visuelle des captures.',en:'Capture visual overhaul.'},shiny],
['zone-unlock','🔓','Feedback',{fr:'Zone débloquée',en:'Zone unlocked'},{fr:'Popup de progression',en:'Progression popup'},{fr:'Carte de déblocage d’une zone.',en:'Zone unlock card.'},unlock],
['rare-sighting','⚡','Feedback',{fr:'Pokémon rare aperçu',en:'Rare sighting'},{fr:'Popup rare + destination',en:'Rare popup + destination'},{fr:'Notification d’apparition rare.',en:'Rare encounter notification.'},rare],
['groudon-fight','🌋','Combats',{fr:'Combat Groudon',en:'Groudon fight'},{fr:'Légendaire dans sa zone',en:'Legendary in its zone'},{fr:'Combat légendaire nouvelle présentation.',en:'New legendary battle presentation.'},l=>legendary(l,'groudon')],
['kyogre-fight','🌊','Combats',{fr:'Combat Kyogre',en:'Kyogre fight'},{fr:'Légendaire dans sa zone',en:'Legendary in its zone'},{fr:'Variante Aqua du combat légendaire.',en:'Aqua legendary battle variant.'},l=>legendary(l,'kyogre')]
].map(([id,icon,category,title,short,description,render])=>({id,icon,category,title,short,description,render:({lang})=>render(lang)}));
export const DEFAULT_SCENE_ID='onboarding-ambush';
export const getScene=id=>SCENES.find(s=>s.id===id)||SCENES.find(s=>s.id===DEFAULT_SCENE_ID)||SCENES[0];
export const sceneText=(scene,key,lang)=>scene?.[key]?.[lang]??scene?.[key]?.en??scene?.[key]?.fr??'';
