-- Pokegang Game / Pokeforge Supabase schema
-- Run this in the Supabase SQL Editor for the project used by config.js.
--
-- This file covers every table currently used by:
-- - modules/systems/cloudAccount.js
-- - modules/systems/gangCompetition.js
--
-- It is safe to rerun for normal updates: policies are recreated and missing
-- columns are added. If an existing table has a different primary key shape,
-- fix that manually before relying on upserts.

-- Optional UUID helper. Supabase projects usually already provide gen_random_uuid().
create extension if not exists pgcrypto;

-- ============================================================================
-- Cloud save: one current save per authenticated user and local save slot.
-- ============================================================================

create table if not exists public.pokegang_saves (
  user_id  uuid        not null references auth.users(id) on delete cascade,
  slot     integer     not null default 0,
  state    jsonb       not null,
  saved_at timestamptz not null default now(),
  primary key (user_id, slot)
);

alter table public.pokegang_saves add column if not exists user_id uuid references auth.users(id) on delete cascade;
alter table public.pokegang_saves add column if not exists slot integer not null default 0;
alter table public.pokegang_saves add column if not exists state jsonb not null default '{}'::jsonb;
alter table public.pokegang_saves add column if not exists saved_at timestamptz not null default now();

alter table public.pokegang_saves enable row level security;

drop policy if exists "player_saves_select_own" on public.pokegang_saves;
drop policy if exists "player_saves_insert_own" on public.pokegang_saves;
drop policy if exists "player_saves_update_own" on public.pokegang_saves;
drop policy if exists "player_saves_delete_own" on public.pokegang_saves;

create policy "player_saves_select_own"
  on public.pokegang_saves for select
  to authenticated
  using ((select auth.uid()) = user_id);

create policy "player_saves_insert_own"
  on public.pokegang_saves for insert
  to authenticated
  with check ((select auth.uid()) = user_id);

create policy "player_saves_update_own"
  on public.pokegang_saves for update
  to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

create policy "player_saves_delete_own"
  on public.pokegang_saves for delete
  to authenticated
  using ((select auth.uid()) = user_id);

create index if not exists player_saves_user_slot_idx on public.pokegang_saves(user_id, slot);

-- ============================================================================
-- Rolling snapshots: two recent restore points per authenticated user and slot.
-- ============================================================================

create table if not exists public.pokegang_save_snapshots (
  id        bigint generated by default as identity primary key,
  user_id   uuid        not null references auth.users(id) on delete cascade,
  slot      integer     not null default 0,
  state     jsonb       not null,
  gang_name text        not null default 'Team ???',
  rep       bigint      not null default 0,
  saved_at  timestamptz not null default now()
);

alter table public.pokegang_save_snapshots add column if not exists user_id uuid references auth.users(id) on delete cascade;
alter table public.pokegang_save_snapshots add column if not exists slot integer not null default 0;
alter table public.pokegang_save_snapshots add column if not exists state jsonb not null default '{}'::jsonb;
alter table public.pokegang_save_snapshots add column if not exists gang_name text not null default 'Team ???';
alter table public.pokegang_save_snapshots add column if not exists rep bigint not null default 0;
alter table public.pokegang_save_snapshots add column if not exists saved_at timestamptz not null default now();

alter table public.pokegang_save_snapshots enable row level security;

drop policy if exists "save_snapshots_select_own" on public.pokegang_save_snapshots;
drop policy if exists "save_snapshots_insert_own" on public.pokegang_save_snapshots;
drop policy if exists "save_snapshots_update_own" on public.pokegang_save_snapshots;
drop policy if exists "save_snapshots_delete_own" on public.pokegang_save_snapshots;

create policy "save_snapshots_select_own"
  on public.pokegang_save_snapshots for select
  to authenticated
  using ((select auth.uid()) = user_id);

create policy "save_snapshots_insert_own"
  on public.pokegang_save_snapshots for insert
  to authenticated
  with check ((select auth.uid()) = user_id);

create policy "save_snapshots_update_own"
  on public.pokegang_save_snapshots for update
  to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

create policy "save_snapshots_delete_own"
  on public.pokegang_save_snapshots for delete
  to authenticated
  using ((select auth.uid()) = user_id);

create index if not exists save_snapshots_user_slot_saved_idx
  on public.pokegang_save_snapshots(user_id, slot, saved_at desc);

-- ============================================================================
-- Authenticated player profile row. This supports the account-cloud path.
-- The public pokegang_leaderboard below is the row used for visible rankings.
-- ============================================================================

create table if not exists public.pokegang_players (
  user_id              uuid        primary key references auth.users(id) on delete cascade,
  gang_name            text        not null default 'Team ???',
  boss_name            text        not null default 'Boss',
  reputation           bigint      not null default 0,
  total_caught         integer     not null default 0,
  total_sold           integer     not null default 0,
  shiny_count          integer     not null default 0,
  shiny_species_count  integer     not null default 0,
  dex_kanto_count      integer     not null default 0,
  dex_national_count   integer     not null default 0,
  agents_count         integer     not null default 0,
  agents_elite_count   integer     not null default 0,
  updated_at           timestamptz not null default now()
);

alter table public.pokegang_players add column if not exists gang_name text not null default 'Team ???';
alter table public.pokegang_players add column if not exists boss_name text not null default 'Boss';
alter table public.pokegang_players add column if not exists reputation bigint not null default 0;
alter table public.pokegang_players add column if not exists total_caught integer not null default 0;
alter table public.pokegang_players add column if not exists total_sold integer not null default 0;
alter table public.pokegang_players add column if not exists shiny_count integer not null default 0;
alter table public.pokegang_players add column if not exists shiny_species_count integer not null default 0;
alter table public.pokegang_players add column if not exists dex_kanto_count integer not null default 0;
alter table public.pokegang_players add column if not exists dex_national_count integer not null default 0;
alter table public.pokegang_players add column if not exists agents_count integer not null default 0;
alter table public.pokegang_players add column if not exists agents_elite_count integer not null default 0;
alter table public.pokegang_players add column if not exists updated_at timestamptz not null default now();

alter table public.pokegang_players enable row level security;

drop policy if exists "players_select_own" on public.pokegang_players;
drop policy if exists "players_insert_own" on public.pokegang_players;
drop policy if exists "players_update_own" on public.pokegang_players;
drop policy if exists "players_delete_own" on public.pokegang_players;

create policy "players_select_own"
  on public.pokegang_players for select
  to authenticated
  using ((select auth.uid()) = user_id);

create policy "players_insert_own"
  on public.pokegang_players for insert
  to authenticated
  with check ((select auth.uid()) = user_id);

create policy "players_update_own"
  on public.pokegang_players for update
  to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

create policy "players_delete_own"
  on public.pokegang_players for delete
  to authenticated
  using ((select auth.uid()) = user_id);

-- ============================================================================
-- Public pokegang_leaderboard. This intentionally allows anonymous browser writes because
-- the current game supports pokegang_leaderboard rows without an authenticated account.
-- For an anti-cheat pokegang_leaderboard, replace these writes with an Edge Function.
-- ============================================================================

create table if not exists public.pokegang_leaderboard (
  token                 text        primary key,
  user_id               uuid        references auth.users(id) on delete set null,
  gang_name             text        not null default 'Team ???',
  boss_name             text        not null default 'Boss',
  boss_sprite           text,
  reputation            bigint      not null default 0,
  total_caught          integer     not null default 0,
  shiny_count           integer     not null default 0,
  shiny_species_count   integer     not null default 0,
  dex_kanto_count       integer     not null default 0,
  dex_national_count    integer     not null default 0,
  total_sold            integer     not null default 0,
  total_money_earned    bigint      not null default 0,
  agents_count          integer     not null default 0,
  is_anonymous          boolean     not null default true,
  updated_at            timestamptz not null default now(),
  month_key             text        not null default '',
  rep_monthly           bigint      not null default 0,
  caught_monthly        integer     not null default 0,
  shiny_monthly         integer     not null default 0,
  shiny_species_monthly integer     not null default 0
);

alter table public.pokegang_leaderboard add column if not exists user_id uuid references auth.users(id) on delete set null;
alter table public.pokegang_leaderboard add column if not exists gang_name text not null default 'Team ???';
alter table public.pokegang_leaderboard add column if not exists boss_name text not null default 'Boss';
alter table public.pokegang_leaderboard add column if not exists boss_sprite text;
alter table public.pokegang_leaderboard add column if not exists reputation bigint not null default 0;
alter table public.pokegang_leaderboard add column if not exists total_caught integer not null default 0;
alter table public.pokegang_leaderboard add column if not exists shiny_count integer not null default 0;
alter table public.pokegang_leaderboard add column if not exists shiny_species_count integer not null default 0;
alter table public.pokegang_leaderboard add column if not exists dex_kanto_count integer not null default 0;
alter table public.pokegang_leaderboard add column if not exists dex_national_count integer not null default 0;
alter table public.pokegang_leaderboard add column if not exists total_sold integer not null default 0;
alter table public.pokegang_leaderboard add column if not exists total_money_earned bigint not null default 0;
alter table public.pokegang_leaderboard add column if not exists agents_count integer not null default 0;
alter table public.pokegang_leaderboard add column if not exists is_anonymous boolean not null default true;
alter table public.pokegang_leaderboard add column if not exists updated_at timestamptz not null default now();
alter table public.pokegang_leaderboard add column if not exists month_key text not null default '';
alter table public.pokegang_leaderboard add column if not exists rep_monthly bigint not null default 0;
alter table public.pokegang_leaderboard add column if not exists caught_monthly integer not null default 0;
alter table public.pokegang_leaderboard add column if not exists shiny_monthly integer not null default 0;
alter table public.pokegang_leaderboard add column if not exists shiny_species_monthly integer not null default 0;

alter table public.pokegang_leaderboard enable row level security;

drop policy if exists "leaderboard_read_public" on public.pokegang_leaderboard;
drop policy if exists "leaderboard_insert_public" on public.pokegang_leaderboard;
drop policy if exists "leaderboard_update_public" on public.pokegang_leaderboard;

create policy "leaderboard_read_public"
  on public.pokegang_leaderboard for select
  to anon, authenticated
  using (true);

create policy "leaderboard_insert_public"
  on public.pokegang_leaderboard for insert
  to anon, authenticated
  with check (true);

create policy "leaderboard_update_public"
  on public.pokegang_leaderboard for update
  to anon, authenticated
  using (true)
  with check (true);

create index if not exists leaderboard_reputation_idx on public.pokegang_leaderboard(reputation desc);
create index if not exists leaderboard_month_rep_idx on public.pokegang_leaderboard(month_key, rep_monthly desc);
create index if not exists leaderboard_caught_idx on public.pokegang_leaderboard(total_caught desc);
create index if not exists leaderboard_money_idx on public.pokegang_leaderboard(total_money_earned desc);
create index if not exists leaderboard_updated_idx on public.pokegang_leaderboard(updated_at desc);

-- ============================================================================
-- PvP gang competition: published defenses.
-- defense_pokemon stores the active 3-Pokemon Boss team snapshot.
-- defense_agent stores up to 3 defender agents in JSON form.
-- Legacy single-agent rows are still accepted by the frontend.
-- ============================================================================

create table if not exists public.pokegang_gang_defenses (
  user_id             uuid        primary key references auth.users(id) on delete cascade,
  gang_name           text        not null default 'Team ???',
  boss_name           text        not null default 'Boss',
  boss_sprite         text,
  reputation_snapshot bigint      not null default 0,
  defense_pokemon     jsonb       not null default '[]'::jsonb,
  defense_agent       jsonb, -- array of up to 3 defender agents; legacy rows may contain a single object
  defense_zone        text,
  updated_at          timestamptz not null default now()
);

alter table public.pokegang_gang_defenses add column if not exists gang_name text not null default 'Team ???';
alter table public.pokegang_gang_defenses add column if not exists boss_name text not null default 'Boss';
alter table public.pokegang_gang_defenses add column if not exists boss_sprite text;
alter table public.pokegang_gang_defenses add column if not exists reputation_snapshot bigint not null default 0;
alter table public.pokegang_gang_defenses add column if not exists defense_pokemon jsonb not null default '[]'::jsonb;
alter table public.pokegang_gang_defenses add column if not exists defense_agent jsonb;
alter table public.pokegang_gang_defenses add column if not exists defense_zone text;
alter table public.pokegang_gang_defenses add column if not exists boss_title text;
alter table public.pokegang_gang_defenses add column if not exists updated_at timestamptz not null default now();

alter table public.pokegang_gang_defenses enable row level security;

drop policy if exists "gang_defenses_read_public" on public.pokegang_gang_defenses;
drop policy if exists "gang_defenses_insert_own" on public.pokegang_gang_defenses;
drop policy if exists "gang_defenses_update_own" on public.pokegang_gang_defenses;
drop policy if exists "gang_defenses_delete_own" on public.pokegang_gang_defenses;

create policy "gang_defenses_read_public"
  on public.pokegang_gang_defenses for select
  to anon, authenticated
  using (true);

create policy "gang_defenses_insert_own"
  on public.pokegang_gang_defenses for insert
  to authenticated
  with check ((select auth.uid()) = user_id);

create policy "gang_defenses_update_own"
  on public.pokegang_gang_defenses for update
  to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

create policy "gang_defenses_delete_own"
  on public.pokegang_gang_defenses for delete
  to authenticated
  using ((select auth.uid()) = user_id);

create index if not exists gang_defenses_rep_idx on public.pokegang_gang_defenses(reputation_snapshot desc);
create index if not exists gang_defenses_updated_idx on public.pokegang_gang_defenses(updated_at desc);

-- ============================================================================
-- PvP gang competition: raid log and defender acknowledgements.
-- Raids no longer transfer reputation. `rep_delta` is retained as a legacy
-- audit field so older rows and app code can coexist during migration.
-- ============================================================================

create table if not exists public.pokegang_gang_raids (
  id                uuid        primary key default gen_random_uuid(),
  attacker_id       uuid        not null references auth.users(id) on delete cascade,
  defender_id       uuid        not null references auth.users(id) on delete cascade,
  attacker_gang     text        not null default 'Team ???',
  defender_gang     text        not null default 'Team ???',
  result            text        not null,
  rep_delta         integer     not null default 0, -- legacy audit field; PvP raids no longer change reputation
  money_penalty     integer     not null default 0,
  defender_snap_rep bigint      not null default 0,
  executed_at       timestamptz not null default now(),
  seen_by_defender  boolean     not null default false,
  constraint gang_raids_result_check check (result in ('attacker_win', 'defender_win'))
);

alter table public.pokegang_gang_raids add column if not exists attacker_id uuid references auth.users(id) on delete cascade;
alter table public.pokegang_gang_raids add column if not exists defender_id uuid references auth.users(id) on delete cascade;
alter table public.pokegang_gang_raids add column if not exists attacker_gang text not null default 'Team ???';
alter table public.pokegang_gang_raids add column if not exists defender_gang text not null default 'Team ???';
alter table public.pokegang_gang_raids add column if not exists result text not null default 'defender_win';
alter table public.pokegang_gang_raids add column if not exists rep_delta integer not null default 0;
alter table public.pokegang_gang_raids add column if not exists money_penalty integer not null default 0;
alter table public.pokegang_gang_raids add column if not exists defender_snap_rep bigint not null default 0;
alter table public.pokegang_gang_raids add column if not exists executed_at timestamptz not null default now();
alter table public.pokegang_gang_raids add column if not exists seen_by_defender boolean not null default false;

alter table public.pokegang_gang_raids enable row level security;

-- Defenders only need to acknowledge raids from the browser. Keep other raid
-- result columns immutable from the client after insertion.
revoke update on public.pokegang_gang_raids from anon, authenticated;
grant update (seen_by_defender) on public.pokegang_gang_raids to authenticated;

drop policy if exists "gang_raids_insert_attacker" on public.pokegang_gang_raids;
drop policy if exists "gang_raids_select_participant" on public.pokegang_gang_raids;
drop policy if exists "gang_raids_update_defender" on public.pokegang_gang_raids;

create policy "gang_raids_insert_attacker"
  on public.pokegang_gang_raids for insert
  to authenticated
  with check ((select auth.uid()) = attacker_id);

create policy "gang_raids_select_participant"
  on public.pokegang_gang_raids for select
  to authenticated
  using ((select auth.uid()) = attacker_id or (select auth.uid()) = defender_id);

create policy "gang_raids_update_defender"
  on public.pokegang_gang_raids for update
  to authenticated
  using ((select auth.uid()) = defender_id)
  with check ((select auth.uid()) = defender_id);

create index if not exists gang_raids_defender_pending_idx
  on public.pokegang_gang_raids(defender_id, seen_by_defender, executed_at desc);
create index if not exists gang_raids_attacker_idx
  on public.pokegang_gang_raids(attacker_id, executed_at desc);
create index if not exists gang_raids_defender_idx
  on public.pokegang_gang_raids(defender_id, executed_at desc);
